<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-7FRJBO5L" failures="2" tests="8" name="Test" time="0.077" errors="0" timestamp="2021-11-30T08:50:28 IST">
  <testcase classname="com.testng.My_Test" name="passWord" time="0.01">
    <skipped/>
  </testcase> <!-- passWord -->
  <testcase classname="com.testng.My_Test" name="passWord" time="0.001">
    <skipped/>
  </testcase> <!-- passWord -->
  <testcase classname="com.testng.My_Test" name="passWord" time="0.002">
    <skipped/>
  </testcase> <!-- passWord -->
  <testcase classname="com.testng.My_Test" name="passWord" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [12345] but found [54321]">
      <![CDATA[java.lang.AssertionError: expected [12345] but found [54321]
at com.testng.My_Test.passWord(My_Test.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- passWord -->
  <testcase classname="com.testng.My_Test" name="uName" time="0.001">
    <skipped/>
  </testcase> <!-- uName -->
  <testcase classname="com.testng.My_Test" name="uName" time="0.001">
    <skipped/>
  </testcase> <!-- uName -->
  <testcase classname="com.testng.My_Test" name="uName" time="0.0">
    <skipped/>
  </testcase> <!-- uName -->
  <testcase classname="com.testng.My_Test" name="uName" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Sashwin] but found [Sanvika]">
      <![CDATA[java.lang.AssertionError: expected [Sashwin] but found [Sanvika]
at com.testng.My_Test.uName(My_Test.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- uName -->
</testsuite> <!-- Test -->
